name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - ci/cd
  pull_request:
    branches:
      - ci/cd

jobs:
  build:
    name: Archive and Export
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Archive App
        run: |
          xcodebuild archive -project ritmix.xcodeproj \
            -scheme ritmix \
            -archivePath build/ritmix.xcarchive \
            -allowProvisioningUpdates
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM="{{ secret.TEAM_ID }}"

      - name: Export IPA for Internal TestFlight
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ritmix.xcarchive \
            -exportOptionsPlist InternalExportOptions.plist \
            -exportPath build/

  upload:
    name: Upload to TestFlight (Internal)
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload to App Store Connect
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun altool --upload-app -f $GITHUB_WORKSPACE/build/ritmix.ipa -t ios --apiKey ${{ secrets.APP_STORE_API_KEY_ID }} --apiIssuer ${{ secrets.APP_STORE_API_ISSUER_ID }}
